version: "3"
services:
  app:
    image: bhongy/vscode-remote-devcontainer.go
    volumes:
      - ..:/workspaces/go-web-programming-book:delegated
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"