version: "3"
services:
  app:
    image: bhongy/vscode-remote-devcontainer.go
    volumes:
      - ..:/workspaces/go-web-programming-book:delegated
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: .env
    depends_on:
      - database
    # security and capability needed for ptrace-based debugger for golang
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  database:
    image: postgres:12.4-alpine
    restart: unless-stopped
    user: postgres
    env_file: .env
